FinalGroupMVCPrj/Controllers/LessonReviewController.cs
using FinalGroupMVCPrj.Models;
using FinalGroupMVCPrj.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Build.Framework.Profiler;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;

namespace FinalGroupMVCPrj.Controllers
{
    [AllowAnonymous]
    public class LessonReviewController : Controller
    {
        private readonly LifeShareLearnContext _context;
        public LessonReviewController(LifeShareLearnContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GetAvgEvalScore(int CourseId)
        {
            var FCode = _context.TLessonCourses.FirstOrDefault(l => l.FLessonCourseId == CourseId).FCode;
            var detail = await _context.TLessonEvaluations
            .Include(order => order.FOrderDetail)
                .ThenInclude(evaluation => evaluation.FLessonCourse)
            .Where(eval => eval.FOrderDetail.FLessonCourse.FCode == FCode)
            .Select(querystring => new LessonAvgEvalViewModel
            {
                FAvgScore = querystring.FScore
            }).ToListAsync();

            double averageScore = Math.Round(detail.Select(x => x.FAvgScore).DefaultIfEmpty(0).Average(), 1);

            var avgScore = new LessonAvgEvalViewModel();
            avgScore.FAvgScore = averageScore;

            return PartialView("_BValuateAvgPartial", avgScore);
        }

        [HttpGet]
        public async Task<IActionResult> GetEvalList(int? CourseId)
        {
            var FCode = _context.TLessonCourses.FirstOrDefault(l => l.FLessonCourseId == CourseId).FCode;
            var query = await _context.TLessonEvaluations
                        .Include(order => order.FOrderDetail)
                             .ThenInclude(course => course.FLessonCourse)
                         .Include(order => order.FOrderDetail)
                            .ThenInclude(od => od.FOrder)
                            .ThenInclude(o => o.FMember)
                        .Where(eval => eval.FOrderDetail.FLessonCourse.FCode == FCode)
                        .Select(evaluation => new LessonEvaluationsViewModel
                        {
                            FLessonEvalId = evaluation.FLessonEvalId,
                            FMemberId = evaluation.FOrderDetail.FOrder.FMemberId,
                            FShowName = evaluation.FOrderDetail.FOrder.FMember.FShowName,
                            FOrderDetailId = evaluation.FOrderDetailId,
                            FLessonCourseId = evaluation.FOrderDetail.FLessonCourseId,
                            FName = evaluation.FOrderDetail.FLessonCourse.FName,
                            FScore = evaluation.FScore,
                            FComment = evaluation.FComment,
                            FCommentDate = evaluation.FCommentDate,
                            FCommentUpdateDate = evaluation.FCommentUpdateDate,
                            FDisplayStatus = evaluation.FDisplayStatus
                        }).OrderByDescending(eval => eval.FCommentDate).ToListAsync();
            int star1 = 0, star2 = 0, star3 = 0, star4 = 0, star5 = 0;

            foreach (var item in query)
            {
                if (item.FScore == 1) star1++;
                else if (item.FScore == 2) star2++;
                else if (item.FScore == 3) star3++;
                else if (item.FScore == 4) star4++;
                else if (item.FScore == 5) star5++;
            }

            int totalCount = star1 + star2 + star3 + star4 + star5;
            int percentStar1 = 0, percentStar2 = 0, percentStar3 = 0, percentStar4 = 0, percentStar5 = 0;

            if (totalCount > 0)
            {
                percentStar1 = (int)Math.Round((double)star1 / totalCount * 100);
                percentStar2 = (int)Math.Round((double)star2 / totalCount * 100);
                percentStar3 = (int)Math.Round((double)star3 / totalCount * 100);
                percentStar4 = (int)Math.Round((double)star4 / totalCount * 100);
                percentStar5 = (int)Math.Round((double)star5 / totalCount * 100);
            }
            ViewBag.totalCount = totalCount;
            ViewBag.percentStar1 = percentStar1;
            ViewBag.percentStar2 = percentStar2;
            ViewBag.percentStar3 = percentStar3;
            ViewBag.percentStar4 = percentStar4;
            ViewBag.percentStar5 = percentStar5;

            return PartialView("_BEvalListPartial", query);
        }

        [HttpGet]
        public async Task<IActionResult> GetEvalDetail(int FOrderDetailId)
        {
            var details = await _context.TLessonEvaluations.Where(eval => eval.FOrderDetailId == FOrderDetailId)
            .Select(eval => new SingleEvaluationViewModel
            {
                FOrderDetailId = FOrderDetailId,
                FScore = eval.FScore,
                FComment = eval.FComment,
                FCommentDate = eval.FCommentDate,
                FCommentUpdateDate = eval.FCommentUpdateDate,
            }).ToListAsync();
            if (details.IsNullOrEmpty())
            {
                return Content("");
            }
            var detail = details.FirstOrDefault();
            return PartialView("_BEvalDetailPartial", detail);
        }

        [HttpGet]
        //獲取照片
        public async Task<FileResult> GetPicture(int FMemberId)
        {
            Models.TMember? member = await _context.TMembers.FindAsync(FMemberId);
            byte[]? Content = member?.FMemberProfilePic;
            return File(Content, "image/jpeg");
        }

        [HttpGet]
        public async Task<IActionResult> isEvaluated(int FOrderDetailId)
        {
            bool isExisting = await _context.TLessonEvaluations.AnyAsync(eval => eval.FOrderDetailId == FOrderDetailId);

            return Json(new { isExisting = isExisting });
        }

        [HttpGet]
        public async Task<IActionResult> canEvaluated(int FOrderDetailId)
        {

            var od = await _context.TOrderDetails
                .Include(od => od.FLessonCourse)
                .FirstOrDefaultAsync(od => od.FOrderDetailId == FOrderDetailId);

            var isValid = od.FOrderValid;
            if (od.FLessonCourse.FLessonDate > DateTime.Now)
            {
                isValid = false;
            }
            return Json(new { isValid = isValid });
        }


        [HttpGet]
        public async Task<IActionResult> CreateEvaluation(int FOrderDetailId)
        {
            return PartialView("_BCreateEvaluationPartial");
        }

        [HttpPost]
        public async Task<IActionResult> CreateEvaluation([FromBody] SingleEvaluationViewModel evaldata)
        {
            if (!(_context.TLessonEvaluations.Any(eval => eval.FOrderDetailId == evaldata.FOrderDetailId)))
            {
                TLessonEvaluation evaluation = new TLessonEvaluation();
                var FmemberId = await _context.TOrderDetails
                    .Include(eval => eval.FOrder)
                    .Where(eval => eval.FOrderDetailId == evaldata.FOrderDetailId)
                    .Select(eval => eval.FOrder.FMemberId).FirstOrDefaultAsync();
                evaluation.FMemberId = FmemberId;
                evaluation.FOrderDetailId = evaldata.FOrderDetailId;
                evaluation.FScore = evaldata.FScore;
                evaluation.FComment = evaldata.FComment;
                evaluation.FCommentDate = DateTime.Now;
                evaluation.FDisplayStatus = true;
                if (ModelState.IsValid)
                {
                    _context.Add(evaluation);
                    await _context.SaveChangesAsync();
                    return Ok("Success");
                }
            }
            return BadRequest("Evaluation creation failed");
        }

        [HttpGet]
        public async Task<IActionResult> EditEvaluation(int FOrderDetailId)
        {
            if (FOrderDetailId == null || _context.TLessonEvaluations == null)
            {
                return NotFound();
            }
            var evaluation = await _context.TLessonEvaluations.FirstOrDefaultAsync(eval => eval.FOrderDetailId == FOrderDetailId);
            if (evaluation == null)
            {
                evaluation = new TLessonEvaluation
                {
                    FScore = 0,
                    FComment = ""
                };
            }
            return PartialView("_BEditEvaluationPartial", evaluation);
        }

        [HttpPost]
        public async Task<IActionResult> EditEvaluation([FromBody] SingleEvaluationViewModel evaldata)
        {
            if (_context.TLessonEvaluations.Any(eval => eval.FOrderDetailId == evaldata.FOrderDetailId))
            {
                var evaluation = await _context.TLessonEvaluations
                    .Include(eval => eval.FOrderDetail)
                        .ThenInclude(eval => eval.FOrder)
                    .Where(eval => eval.FOrderDetailId == evaldata.FOrderDetailId).FirstOrDefaultAsync();
                evaluation.FScore = evaldata.FScore;
                evaluation.FComment = evaldata.FComment;
                evaluation.FCommentUpdateDate = DateTime.Now;
                if (ModelState.IsValid)
                {
                    _context.Update(evaluation);
                    await _context.SaveChangesAsync();
                    return Ok("Success");
                }
            }
            return BadRequest("Evaluation creation failed");
        }


        [HttpGet]
        public async Task<IActionResult> GetEvalScore(int FOrderDetailId)
        {
            if (FOrderDetailId == null || _context.TLessonEvaluations == null)
            {
                return NotFound();
            }

FinalGroupMVCPrj/Views/LessonReview/_BCreateEvaluationPartial.cshtml
@model TLessonEvaluation
<div class="modal fade" id="evalModal" tabindex="-1" aria-labelledby="evalModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-xl" style="width:550px;">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="evalModalLabel">評價</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" id="CreateCancel"></button>
            </div>
            <form id="CreateForm">
                <div class="modal-body" style="display: flex; justify-content: center;">
                    <div class="rating" data-vote="0">

                        <div class="star hidden" style="display: none;">
                            <span class="full" data-value="0"></span>
                        </div>

                        <div class="star">
                            <span class="full" data-value="1"></span>
                            <span class="selected"></span>
                        </div>

                        <div class="star">
                            <span class="full" data-value="2"></span>
                            <span class="selected"></span>
                        </div>

                        <div class="star">
                            <span class="full" data-value="3"></span>
                            <span class="selected"></span>
                        </div>

                        <div class="star">
                            <span class="full" data-value="4"></span>
                            <span class="selected"></span>
                        </div>

                        <div class="star">
                            <span class="full" data-value="5"></span>
                            <span class="selected"></span>
                        </div>

                        <div class="score">
                            <span class="score-rating js-score" id="ratingScore">0</span>
                            <span>/</span>
                            <span class="total">5</span>
                        </div>
                    </div>

                </div>
                <!--評價內容部分-->

                <div class="mb-3">
                    <label for="evalContent" class="form-label" style="display:flex;justify-content:center;">評價內容</label>
                    <textarea class="form-control" style=" width:400px; height:auto; margin-left:auto;margin-right:auto;" id="evalContent" rows="6"></textarea>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" id="CreateCancel">取消</button>
                    <button type="submit" class="btn btn-primary" id="scoreSubbtn">評價</button>
                </div>
            </form>
            <button class="btn  btn-sm rounded-pill" id="createdemo">demo1</button>
        </div>
    </div>
</div>

<script>

</script>

FinalGroupMVCPrj/Views/LessonReview/_BEditEvaluationPartial.cshtml
@model TLessonEvaluation
<div class="modal fade" id="editEvalModal" tabindex="-1" aria-labelledby="editEvalModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-xl" style="width:550px;">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editEvalModalLabel">評價</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" id="EditCancel"></button>
            </div>
            <form id="EditForm">
                <div class="modal-body" style="display: flex; justify-content: center;">
                    <div class="rating" data-vote="0">

                        <div class="star hidden" style="display: none;">
                            <span class="full" data-value="0"></span>
                        </div>

                        <div class="star">
                            <span class="full" data-value="1"></span>
                            <span class="selected"></span>
                        </div>

                        <div class="star">
                            <span class="full" data-value="2"></span>
                            <span class="selected"></span>
                        </div>

                        <div class="star">
                            <span class="full" data-value="3"></span>
                            <span class="selected"></span>
                        </div>

                        <div class="star">
                            <span class="full" data-value="4"></span>
                            <span class="selected"></span>
                        </div>

                        <div class="star">
                            <span class="full" data-value="5"></span>
                            <span class="selected"></span>
                        </div>

                        <div class="score">
                            <input asp-for="FScore" style="display:none;" />
                            <span class="score-rating js-score" id="editRatingScore" score="@Model.FScore">@Model.FScore</span>
                            <span>/</span>
                            <span class="total">5</span>
                        </div>
                    </div>

                </div>
                <!--評價內容部分-->

                <div class="mb-3">
                    <label for="editComment" class="form-label" style="display:flex;justify-content:center;">評價內容</label>
                    <textarea asp-for="FComment" class="form-control" style=" width:400px; height:auto; margin-left:auto;margin-right:auto;" id="editComment" rows="6"></textarea>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" id="EditCancel">取消</button>
                    <button type="submit" class="btn btn-primary" id="scoreEditbtn">修改評價</button>
                </div>
            </form>
            <button class="btn  btn-sm rounded-pill" id="editdemo">demo1</button>
        </div>
    </div>
</div>

FinalGroupMVCPrj/Views/LessonReview/_BValuatePartial.cshtml
@model IEnumerable<LessonEvaluationsViewModel>
<!-- 評價 -->
<div class="tab-pane slide" id="tab5">
    <div class="review-progresses p-30 radius-md border mb-40">
        <div class="d-flex flex-wrap align-items-center justify-content-between gap-3 mb-30">
            <h4 class="mb-0">全部評價狀態</h4>
            <div class="ratings size-md">
                <div class="rate bg-img" data-bg-image="/images/rate-star-md.png">
                    <div class="rating-icon bg-img" data-bg-image="/images/rate-star-md.png"></div>
                </div>
                <span class="ratings-total">(@ViewBag.totalCount)</span>
            </div>
        </div>
        <div class="review-progress mb-10 row align-items-center">
            <div class="col-3 col-sm-2">5 星</div>
            <div class="progress-line col-6 col-sm-8">
                <div class="progress">
                    <div class="progress-bar bg-primary" style="width: @ViewBag.percentStar5%" role="progressbar" aria-label="Basic example" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
            </div>
            <div class="col-3 col-sm-2 text-end">@ViewBag.percentStar5%</div>
        </div>
        <div class="review-progress mb-10 row align-items-center">
            <div class="col-3 col-sm-2">4 星</div>
            <div class="progress-line col-6 col-sm-8">
                <div class="progress">
                    <div class="progress-bar bg-primary" style="width: @ViewBag.percentStar4%" role="progressbar" aria-label="Basic example" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
            </div>
            <div class="col-3 col-sm-2 text-end">@ViewBag.percentStar4%</div>
        </div>
        <div class="review-progress mb-10 row align-items-center">
            <div class="col-3 col-sm-2">3 星</div>
            <div class="progress-line col-6 col-sm-8">
                <div class="progress">
                    <div class="progress-bar bg-primary" style="width: @ViewBag.percentStar3%" role="progressbar" aria-label="Basic example" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
            </div>
            <div class="col-3 col-sm-2 text-end">@ViewBag.percentStar3%</div>
        </div>
        <div class="review-progress mb-10 row align-items-center">
            <div class="col-3 col-sm-2">2 星</div>
            <div class="progress-line col-6 col-sm-8">
                <div class="progress">
                    <div class="progress-bar bg-primary" style="width: @ViewBag.percentStar2%" role="progressbar" aria-label="Basic example" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
            </div>
            <div class="col-3 col-sm-2 text-end">@ViewBag.percentStar2%</div>
        </div>
        <div class="review-progress mb-10 row align-items-center">
            <div class="col-3 col-sm-2">1 星</div>
            <div class="progress-line col-6 col-sm-8">
                <div class="progress">
                    <div class="progress-bar bg-primary" style="width: @ViewBag.percentStar1%" role="progressbar" aria-label="Basic example" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
            </div>
            <div class="col-3 col-sm-2 text-end">@ViewBag.percentStar1%</div>
        </div>
    </div>

    <div class="review-box pb-10">
        @foreach (var item in Model)
        {
            <div class="review-list mb-30 border radius-md">
                <div class="review-item p-30">
                    <div class="review-header flex-wrap mb-20">
                        <div class="author d-flex align-items-center justify-content-between gap-3">
                            <div class="author-img">
                                <div class="lazy-container ratio ratio-1-1 rounded-circle">
                                        <img FMemberId="@item.FMemberId" src="/images/OwenAdd/memberNoPhoto.jpg" data-src="@Url.Action("GetPicture", "LessonReview", new { FMemberId = item.FMemberId })" title="@item.FName" class="lazyload" />
                                </div>
                        </div>
                        <div class="author-info">
                            <h6 class="mb-1">
                                @item.FShowName
                            </h6>
                            <div class="ratings mb-1">
                                    <div class="rate bg-img" data-bg-image="/images/rate-star.png" style="background-image: url('/images/rate-star.png');">
                                        @{
                                            int width = 0;
                                            switch (item.FScore)
                                            {
                                                case 1:
                                                    width = 20;
                                                    break;
                                                case 2:
                                                    width = 40;
                                                    break;
                                                case 3:
                                                    width = 60;
                                                    break;
                                                case 4:
                                                    width = 80;
                                                       break;
                                                case 5:
                                                    width = 100;
                                                    break;
                                                default:
                                                    width = 0;
                                                    break;
                                            }
                                        }
                                        <div class="rating-icon bg-img" data-bg-image="/images/rate-star.png" style="background-image: url('/images/rate-star.png'); width:@width%"></div>

                                </div>
                                <span class="ratings-total">(@item.FScore)</span>
                            </div>
                        </div>
                    </div>
                    <div class="more-info font-sm">
                        <div class="icon-start">
                            <i class="fa-solid fa-clock"></i>
                                @{
                                    // 獲取評論日期
                                    DateTime commentDate = item.FCommentDate;

                                    // 獲取當前日期
                                    DateTime currentDate = DateTime.Now;

                                    // 計算日期差距
                                    TimeSpan timeDifference = currentDate - commentDate;

                                    // 轉換成幾年幾月幾日的格式
                                    string displayDate = "";
                                    if (timeDifference.Days == 0)
                                    {
                                        displayDate = "今天";
                                    }
                                    else if (timeDifference.Days == 1)
                                    {
                                        displayDate = "昨天";
                                    }

                                    // 如果不是今天或昨天，則顯示完整日期
                                    if (string.IsNullOrEmpty(displayDate))
                                    {
                                        displayDate = commentDate.ToString("yyyy年MM月dd日");
                                    }
                                }

                                @displayDate
                        </div>
                    </div>
                </div>
                <p>
                    @item.FComment
                </p>
            </div>
        </div>
        }

        <!--範例評論-->
@*         <div class="review-list mb-30 border radius-md">
            <div class="review-item p-30">
                <div class="review-header flex-wrap mb-20">
                    <div class="author d-flex align-items-center justify-content-between gap-3">
                        <div class="author-img">
                            <a href="error-404.html" target="_self" title="Link" class="lazy-container ratio ratio-1-1 rounded-circle">
                                <img class="lazyload" src="/images/placeholder.png" data-src="/images/avatar-4.jpg" alt="Avatar">
                            </a>
                        </div>
                        <div class="author-info">
                            <h6 class="mb-1">
                                <a href="error-404.html" target="_self" title="Link">Mark Jco</a>
                            </h6>
                            <div class="ratings mb-1">
                                <div class="rate bg-img" data-bg-image="/images/rate-star.png">
                                    <div class="rating-icon bg-img" data-bg-image="/images/rate-star.png"></div>
                                </div>
                                <span class="ratings-total">(4)</span>
                            </div>
                            <span class="font-xsm icon-start">
                                <span class="color-green">
                                    <i class="fa-solid fa-circle-check" style="color: #00db0f;"></i>
                                </span>
                                Verified User
                            </span>
                        </div>
                    </div>
                    <div class="more-info font-sm">
                        <div class="icon-start">
                            <i class="fa-solid fa-clock"></i>
                            04 Days ago
                        </div>
                    </div>
                </div>
                <h5 class="lc-1">Ana Studios was very logical and creative at the same time</h5>
                <p>
                    The client received excellent feedback on DePalma Studios’ designs due to
                    their website's improved look and feel. The team was very communicative and
                    collaborative, and they demonstrated a unique understanding of the client’s
                    requirements, providing very.
                </p>
            </div>
        </div>
        <div class="review-list mb-30 border radius-md">
            <div class="review-item p-30">
                <div class="review-header flex-wrap mb-20">
                    <div class="author d-flex align-items-center justify-content-between gap-3">
                        <div class="author-img">
                            <a href="error-404.html" target="_self" title="Link" class="lazy-container ratio ratio-1-1 rounded-circle">
                                <img class="lazyload" src="/images/placeholder.png" data-src="/images/avatar-2.jpg" alt="Avatar">
                            </a>
                        </div>
                        <div class="author-info">
                            <h6 class="mb-1">
                                <a href="error-404.html" target="_self" title="Link">Johnny Ben</a>
                            </h6>
                            <div class="ratings mb-1">
                                <div class="rate bg-img" data-bg-image="/images/rate-star.png">
                                    <div class="rating-icon bg-img" data-bg-image="/images/rate-star.png"></div>
                                </div>
                                <span class="ratings-total">(4)</span>
                            </div>
                            <span class="font-xsm icon-start">
                                <span class="color-green">
                                    <i class="fa-solid fa-circle-check" style="color: #00db0f;"></i>
                                </span>
                                Verified User
                            </span>
                        </div>
                    </div>
                    <div class="more-info font-sm">
                        <div class="icon-start">
                            <i class="fa-solid fa-clock"></i>
                            04 Days ago
                        </div>
                    </div>
                </div>
                <h4 class="lc-1">Ana Studios was very logical and creative at the same time</h4>
                <p>
                    The client received excellent feedback on DePalma Studios’ designs due to
                    their website's improved look and feel. The team was very communicative and
                    collaborative, and they demonstrated a unique understanding of the client’s
                    requirements, providing very.
                </p>
            </div>
            </div> 
        </div> *@
@*         <!-- Pagination -->
        <nav class="pagination-nav mb-30">
            <ul class="pagination justify-content-center">
                <li class="page-item">
                    <a class="page-link" href="courses.html" aria-label="Previous">
                        <i class="fa-solid fa-angle-left"></i>
                    </a>
                </li>
                <li class="page-item active"><a class="page-link" href="courses.html">1</a></li>
                <li class="page-item"><a class="page-link" href="courses.html">2</a></li>
                <li class="page-item"><a class="page-link" href="courses.html">3</a></li>
                <li class="page-item">
                    <a class="page-link" href="courses.html" aria-label="Next">
                        <i class="fa-solid fa-angle-right"></i>
                    </a>
                </li>
            </ul>
        </nav> *@