FinalGroupMVCPrj/Models/ViewModels/LessonListViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace FinalGroupMVCPrj.Models.ViewModels
{
    public class LessonListViewModel
    {
        [Display(Name = "代號")]
        public string Code { get; set; }
        [Display(Name = "課程名稱")]
        public string Name { get; set; }
        [Display(Name = "領域")]
        public string Filed { get; set; }
        [Display(Name = "售價")]
        public int Price { get; set; }
      
        [Display(Name = "開課日期")]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}")]
        public DateTime? LessonDate { get; set; }
        [Display(Name = "總時數")]
        public string Time {  get; set; }
        [Display(Name = "人數上限")]
        public int? MaxPeople { get; set; }
        [Display(Name = "報名人數")]
        public int RegPeople { get; set;}
        [Display(Name = "狀態")]
        public string Status { get; set; }
        [Display(Name = "場地類型")]
        public string VenueType { get; set; }

        public int lessonid { get; set; }

    }
}

FinalGroupMVCPrj/Controllers/TeacherAdminController.cs
using FinalGroupMVCPrj.Models;
using FinalGroupMVCPrj.Models.DTO;
using FinalGroupMVCPrj.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.IO;
using System.Net;
using System.Net.Http;
using System.Security.Cryptography.Pkcs;
using System.Security.Policy;
using static NuGet.Packaging.PackagingConstants;
using System.Text;
using static Org.BouncyCastle.Crypto.Engines.SM2Engine;
using Microsoft.CodeAnalysis.FlowAnalysis;
using Newtonsoft.Json.Linq;
using System.Drawing;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace FinalGroupMVCPrj.Controllers
{
    [Authorize(Roles = "Teacher")]
    public class TeacherAdminController : UserInfoController
    {
        private readonly HttpClient _httpClient;
        private IWebHostEnvironment _hostEnv;
        private readonly LifeShareLearnContext _context;
        public TeacherAdminController(LifeShareLearnContext context, IWebHostEnvironment env)
        {
            _context = context;
            _hostEnv = env;
            _httpClient = new HttpClient();
        }
        //■ ==========================     翊妏作業區      ==========================■

        // GET: TeacherAdmin/LessonList
        //動作簡述：回傳老師課程清單資訊
        [HttpGet]
        public IActionResult LessonList()
        {
            return View();
        }
        // GET: TeacherAdmin/LessonList
        //動作簡述：回傳老師課程清單資訊
        [HttpGet]
        public IActionResult ListDataJson()
        {
            var lessons = _context.TLessonCourses.AsQueryable().Where(x => x.FTeacherId == GetCurrentTeacherId()).Select(querystring => new LessonListViewModel
            {
                Code = querystring.FCode,
                Name = querystring.FName,
                Filed = _context.TCourseFields.Where(x => x.FFieldId == querystring.FSubject.FFieldId).Select(x => x.FFieldName).FirstOrDefault(),
                Price = (int)querystring.FPrice,
                LessonDate = querystring.FLessonDate,
                Time = ((querystring.FEndTime.Value.TotalHours == null ? 0 : querystring.FEndTime.Value.TotalHours) - (querystring.FStartTime.Value.TotalHours == null ? 0 : querystring.FStartTime.Value.TotalHours)).ToString() + "hr",
                MaxPeople = querystring.FMaxPeople,
                RegPeople = _context.TOrderDetails.Where(x => x.FLessonCourseId == querystring.FLessonCourseId).Count(),
                Status = querystring.FStatus,
                VenueType = querystring.FVenueType == true ? "實體" : "線上",
                lessonid = querystring.FLessonCourseId
            });
            return Json(new { data = lessons });
        }
        [HttpGet]
        public IActionResult LessonOpen()
        {
            return View();
        }

        [HttpGet]
        public IActionResult LessonCreate(string? code)
        {
            //歷史開課
            if (code != null)
            {
                LessonCreateViewModel lesson = new LessonCreateViewModel();
                var course = _context.TLessonCourses.Where(x => x.FCode == code).FirstOrDefault();
                if (course != null)
                {
                    lesson.FLessonCourseId = course.FLessonCourseId;
                    lesson.FSubjectId = course.FSubjectId;
                    lesson.FSubject = _context.TCourseSubjects.Where(x => x.FSubjectId == lesson.FSubjectId).Select(x => x.FSubjectName).FirstOrDefault();
                    lesson.FFiled = (from s in _context.TCourseSubjects
                                     join f in _context.TCourseFields on s.FFieldId equals f.FFieldId
                                     where s.FSubjectId == course.FSubjectId
                                     select f.FFieldName).Distinct().FirstOrDefault();
                    lesson.FName = course.FName;
                    lesson.FCode = course.FCode;
                    lesson.FTeacherId = GetCurrentTeacherId();

                    //lesson.FPhoto = course.FPhoto==null?null:ConvertByteArrayToIFormFile(course.FPhoto,course.FName);
                    ViewBag.courseType = "old";

                    return View("LCreate", lesson);
                }
            }

            ViewBag.courseType = "new";
            //直接開課
            return View("LCreate", new LessonCreateViewModel());
        }
        // POST: TeacherAdmin/LessonCreate
        [RequestFormLimits(MultipartBodyLengthLimit = 10240000)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LessonCreate(LessonCreateViewModel lesson, string status, string getcourseType)
        {
            int teacherid = GetCurrentTeacherId();
            string code = "";
            try
            {
                TLessonCourse course = new TLessonCourse();
                if (getcourseType == "new")
                {
                    course.FName = lesson.FName;
                    course.FSubjectId = lesson.FSubjectId;
                    course.FSubjectId = Convert.ToInt32(lesson.FSubject);
                    code = loadCode(Convert.ToInt32(lesson.FFiled), course.FSubjectId);
                }
                else if (getcourseType == "old")
                {
                    course.FSubjectId = _context.TCourseSubjects.Where(x => x.FSubjectName == lesson.FSubject).Select(x => x.FSubjectId).FirstOrDefault();
                    course.FName = lesson.FName;

                }

                course.FVenueName = lesson.FVenueName;
                course.FTeacherId = teacherid;
                course.FEditorDes = lesson.FEditorDes;
                var count = _context.TLessonCourses.Where(x => x.FSubjectId == Convert.ToInt32(course.FSubjectId)).Select(x=>x.FCode).Distinct().Count();
                course.FCode = lesson.FCode != null ? lesson.FCode : $"{code}{(count + 1):D3}";
                course.FDescription = lesson.FDescription;
                course.FRequirement = lesson.FRequirement;
                course.FPrice = lesson.FPrice;
                course.FHomeworkDescription = lesson.FHomeworkDescription;
                course.FMaxPeople = lesson.FMaxPeople;
                course.FMinPeople = lesson.FMinPeople;
                course.FLessonDate = lesson.FLessonDate;
                course.FRegDeadline = lesson.FRegDeadline;
                course.FStartTime = lesson.FStartTime;
                course.FEndTime = lesson.FEndTime;
                course.FVenueName = lesson.FVenueName;
                course.FDistrictId = lesson.FDistrictId;
                course.FAddressDetail = lesson.FAddressDetail;
                course.FVenueType = lesson.FVenueType;
                //會議室暫定用固定連結
                course.FOnlineLink = lesson.FVenueType == false ? "https://meet.google.com/tek-pkav-obh" : null;

                course.FStatus = checkStatus(status);
                // course.FPhoto = lesson.FPhoto;
                if (lesson.FPhoto != null)
                {

                    course.FPhoto = await ReadUploadImage(lesson.FPhoto);
                }
                _context.Add(course);
                await _context.SaveChangesAsync();
                if (status == "TempSave")
                {
                    ViewBag.Success = "暫存成功";
                }
                else
                {
                    ViewBag.Success = "開課成功";
                }
                return View("LessonList");
                
            }
            catch (Exception e)
            {
                if (status == "TempSave")
                {
                    ViewBag.Error = "暫存失敗";
                }
                else
                {
                    ViewBag.Error = "開課失敗";
                }
              
            }
            return View("LessonList");

        }

        // GET: TeacherAdmin/LessonEdit/10000
        [HttpGet]
        public async Task<IActionResult> LessonEdit(int? id)
        {
            if (id == null || _context.TLessonCourses == null)
            {
                return NotFound();
            }

            var course = await _context.TLessonCourses.FindAsync(id);
            LessonCreateViewModel lesson = new LessonCreateViewModel();
            if (course == null)
            {
                return NotFound();
            }
            var selectcity= (from s in _context.TCities
              join f in _context.TCityDistricts on s.FCityId equals f.FCityId
             where f.FDistrictId== course.FDistrictId
              select s.FCityId).Distinct().FirstOrDefault();
            var CitySelectList = LessonCreateViewModel.GetCitySelectList();
            foreach (var s in CitySelectList)
            {
                if (s.Value == selectcity.ToString())
                {
                    s.Selected = true;
                    break;
                }
            }

            ViewBag.CitySelectList = CitySelectList;
            ViewBag.DistrictSelect = course.FDistrictId;
            if (course != null)
            {
                lesson.FLessonCourseId = course.FLessonCourseId;
                lesson.FSubjectId = course.FSubjectId;
                lesson.FSubject = _context.TCourseSubjects.Where(x => x.FSubjectId == lesson.FSubjectId).Select(x => x.FSubjectName).FirstOrDefault();
                lesson.FFiled = (from s in _context.TCourseSubjects
                                 join f in _context.TCourseFields on s.FFieldId equals f.FFieldId
                                 where s.FSubjectId == course.FSubjectId
                                 select f.FFieldName).Distinct().FirstOrDefault();
                lesson.FName = course.FName;
                lesson.FCode = course.FCode;
                lesson.FTeacherId = GetCurrentTeacherId();
                lesson.FRequirement = course.FRequirement;
                lesson.FRegDeadline = course.FRegDeadline;

FinalGroupMVCPrj/Views/TeacherAdmin/TRelatedPic.cshtml
@model IEnumerable<TeacherBasicViewModel>
@{
    ViewData["Title"] = "TRelatedPic";
    Layout = "~/Views/Shared/_LayoutTeacherAdmin.cshtml";
}
@section Styles {
    <style>
        .hidden {
            display: none;
        }

        * {
            padding: 0;
            margin: 0;
        }

        /*	general	*/

        section {
            padding: 50px 0;
        }

        /*	gallery */

        .gallery-title {
            font-size: 36px;
            color: #3F6184;
            text-align: center;
            font-weight: 500;
            margin-bottom: 70px;
        }

        .btn btn-outline-secondary {
            font-size: 18px;
            border: 2px solid #3F6184;
            padding: 5px 10px;
            text-align: center;
            color: #3F6184;
            margin-bottom: 30px;
            background: transparent;
        }

        .btn.btn-outline-secondary:hover,
        .btn.btn-outline-secondary:focus,
        .btn.btn-outline-secondary.active {
            color: #ffffff;
            background-color: #3F6184;
            outline: none;
        }

        .gallery_product {
            margin-inline: 20px;
            margin-bottom: 15px;
            padding: 0;
            position: relative;
        }

            .gallery_product .img-info {
                position: absolute;
                background: rgba(0,0,0,0.3);
                left: 0;
                right: -5%;
                bottom: 0;
                padding: 20px;
                overflow: hidden;
                color: #fff;
                top: 0;
                display: none;
                -webkit-transition: 2s;
                transition: 2s;
                text-align: center;
            }

            .gallery_product:hover .img-info {
                display: block;
                -webkit-transition: 2s;
                transition: 2s;
            }

        /*	end gallery */
    </style>
}


<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.css" />
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
<!-- html畫面start -->
<div class="pagetitle" style="margin-left:25px;">
    <h1>相關圖片</h1>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="index.html">老師後台</a></li>
            <li class="breadcrumb-item">老師資料</li>
            <li class="breadcrumb-item active">相關圖片</li>
        </ol>
    </nav>
</div><!-- End Page Title -->
<div class="container-fluid">
    <div class="row">
        <!-- 新增圖片的按鈕 -->
        <div class="text-start" style="margin:10px">
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">新增圖片</button>
        </div>
        <!-- 分類圖片 -->
        <div align="justify" style="margin:10px">
            <button class="btn btn-outline-secondary" data-filter="all">所有</button>
            <button class="btn btn-outline-secondary" data-filter="教育背景">教育背景</button>
            <button class="btn btn-outline-secondary" data-filter="證照證書">證照證書</button>
            <button class="btn btn-outline-secondary" data-filter="作品">作品</button>
        </div>

        <br />
        <div id="divImages" style="display:flex;flex-wrap: wrap;border-color:red">

            <!-- 圖片們 -->
            @foreach (TeacherBasicViewModel item in Model)
            {
                <div>

                    <div style="display: flex; align-items: center;margin-bottom:0" class=" gallery_product col-sm-3 col-xs-6 filter   @item.Category ">
                        <!-- 刪除功能 -->
                        <form asp-controller="TeacherAdmin" asp-action="TdeletePic" method="post" >
                            <input type="hidden" name="id" value="@item.TeacherImagesId" />
                            <button id="btnSubmit" type="button" class="btn btn-danger btn-sm" style="width:35px;height:30px;" title="刪除" onclick="ClickDelete(this)"><i class="bi bi-trash"></i></button>
                        </form>
                        <!-- 編輯功能 -->
                        @* <button class="btn btn-primary btn-sm" style="width:35px;height:30px" title="編輯" data-bs-toggle="modal" data-bs-target="#staticBackdrop" onclick="editPicture(@item.TeacherImagesId)"><i class="fa-solid fa-pencil"></i></button> *@
                        <button class="btn btn-primary btn-sm" style="width:35px;height:30px" title="編輯" data-bs-toggle="modal" data-bs-target="#editModal" onclick="editPicture(@item.TeacherImagesId)"><i class="fa-solid fa-pencil"></i></button>
                    </div>
                    <div class="gallery_product col-sm-3 col-xs-6 filter   @item.Category " style="width:345px;height:240px">
                        <img src="@Url.Action("GetPicture","TeacherAdmin",new {id=item.TeacherImagesId })" title="@item.ImageName" style="width:360px;height:240px" />
                        <div class='img-info'>
                            <h4>@item.ImageName</h4>
                        </div>
                    </div>
                </div>
                @*  <!-- 編輯圖片的modal彈跳視窗-->
            <partial name="T_EditTrPicPartialcopy" model="@item.TeacherImageModel"></partial>   *@

            }
        </div>
    </div>
</div>

<!-- html畫面end -->
<!-- 新增圖片的modal彈跳視窗-->
<partial name="T_CreateTrPicPartial" model="new TTeacherImage()"></partial>
<!-- 編輯圖片的modal彈跳視窗-->
<partial name="T_EditTrPicPartial" model="new TTeacherImage()"></partial>

@section Scripts {
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.js"></script>
    <script>
        /*	gallery */
        $(document).ready(function () {

            $(".btn.btn-outline-secondary").click(function () {
                var value = $(this).attr('data-filter');

                if (value == "all") {
                    $('.filter').show('1000');
                }
                else {
                    $(".filter").not('.' + value).hide('3000');
                    $('.filter').filter('.' + value).show('3000');

                }

                if ($(".btn.btn-outline-secondary").removeClass("active")) {
                    $(this).removeClass("active");
                }
                $(this).addClass("active");
            });
        });
        /*	end gallery */

        $(document).ready(function () {
            $(".fancybox").fancybox({
                openEffect: "none",
                closeEffect: "none"
            });
        });

    </script>
    @* script功能 : 預覽上傳的圖片、 *@
    <script>
        // //判斷有沒有值不斷要有值第一個檔案要有值
        // function previewImage(inputFile, img) {
        //     //判斷檔案控制項有沒有值 且 第一個檔案要有值
        //     if (inputFile.files != null && inputFile.files[0] != null) {
        //         //限制檔案上傳格式
        //         var allowTpye = "image.*";
        //         // 判斷檔案有沒有符合上傳的格式
        //         if (inputFile.files[0].type.match(allowTpye)) {
        //             //上傳檔案並預覽圖片內容
        //             var reader = new FileReader();
        //             //檔案讀取完成後處理load事件//函式參數e抓事件發生的內容
        //             reader.onload = function (e) {
        //                 //console.log(e.target.result)
        //                 //替換頁面檔案，prev():前一個//讀到的檔案內容(e.target.result)丟給src
        //                 //img.attr("src", e.target.result);
        //                 //改title內容，改成name屬性
        //                 //img.attr("title", inputFile.files[0].name);
        //                 img.innerHTML += `<img src="${e.target.result}" style="width:110px;">`;
        //                 //class選擇器:依據樣式選擇器找到btn
        //                 $("#inpSubmit").prop('disabled', false);
        //                 //id選擇器:依據樣式選擇器找到div
        //                 $("#divwarning").hide();
        //             };
        //             //從load事件拿檔案(e.target.result)
        //             reader.readAsDataURL(inputFile.files[0]);
        //         }
        //         else {
        //             //class選擇器:依據樣式選擇器找到btn
        //             $("#inpSubmit").prop('disabled', true);
        //             //id選擇器:依據樣式選擇器找到div
        //             $("#divwarning").show();
        //         }
        //     }
        // }
        // $("#Inputfile").change(function () {
        //     // alert("change");
        //     previewImage(this, $("#previews"));
        // });
       

    </script>
    @* script功能 : 編輯的partialview欄位顯示 *@
    <script>
        async function editPicture(teacherImagesId) {
            const response = await fetch(`@Url.Content("~/TeacherAdmin/EditPartialViewInfo")?teacherImagesId=${teacherImagesId}`)
            const datas = await response.json();
            //console.log(datas)
            document.querySelector('#editfloatingInput').value = datas.imageName;
            document.querySelector('#editselect').value = datas.category;
            document.querySelector('#inputeditimageid').value = datas.imageId;
        }
    </script>
    <script>
        function ClickDelete(t) {
            const form = t.parentNode;
            Swal.fire({
                title: "確認儲存帳號資訊?",
                text: ``,
                icon: "info",
                showCancelButton: true,
                confirmButtonColor: "#30C2EC",
                cancelButtonColor: "#d33",
                confirmButtonText: "確定",
                cancelButtonText: "取消"
            })
                .then(function (result) {
                    if (result.isConfirmed) {
                        form.submit();
                    }
                })
        }
    </script>
}

FinalGroupMVCPrj/Views/TeacherAdmin/T_CreateTrPicPartial.cshtml
@model TTeacherImage
<!-- 新增圖片的modal彈跳視窗-->

<style>
    .dz-preview .dz-progress {
        /* 將進度條透明 */
        /* opacity: 0; */
        display: none;
    }

    .dz-preview .dz-details {
        display: none;
    }

    .dz-preview .dz-error-message {
        display: none;
    }

    .dz-preview .dz-success-mark {
        display: none;
    }

    .dz-preview .dz-error-mark {
        display: none;
    }

    #demoPic > button {
        color: white;
        background-color: white;
        color: white;
        background-color: white
    }

    #demoPic:hover > button {
        background-color: lightgrey;
        color: gray;
    }
</style>

<div class="modal fade" id="exampleModal" tabindex="-100" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <div class="d-flex align-items-center" id="demoPic">
                <h5 class="modal-title" id="exampleModalLabel">上傳圖片</h5>
                    <button id="demoCertificate" class="btn btn-sm rounded-pill">中餐證照</button>
                </div>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form asp-controller="TeacherAdmin" asp-action="TAddtrimage" enctype="multipart/form-data">
                <div class="modal-body" style=" display:flex ;">
                    <!-- 拖曳圖片 -->
                    <div action="TAddtrimage" class="dropzone" id="divdropzone" style="text-align: center;padding:100px; border: 2px dashed  #ADADAD;">
                        <!-- 自訂dropzonejs的預設文字 -->
                        <div class="dz-message" data-dz-message><span></span></div>
                        <img src="~/images/TonyAdd/image_upload_icon.png" /><br>
                        <label>將你要上傳的圖片拖曳到這裡</label>
                        <div id="divwarning" style="display:none">
                            <img src="~/images/TonyAdd/warning.png" style="width:25px" />
                            <label style="color:red;font-size:15px">檔案格式無效。</label>
                        </div>
                        <!-- 上傳圖片按鈕 -->
                        <input asp-for="FImageLink" type="file" id="Inputfile" class="hidden" accept="image/gif, image/jpeg, image/png" multiple />
                        <label for="Inputfile" class="btn btn-primary" title="選取圖片">選取圖片</label>
                        @*  <div style="border:1px solid red;display:none;" class="dz-progress"><span  class="dz-upload" data-dz-uploadprogress></span></div> *@
                    </div>
                    <div style="text-align: center;padding:100px">
                        <div class="form-floating mb-3">
                            <select asp-for="FCategory" class="form-select">
                                <option disabled selected hidden></option>
                                <option value="教育背景">教育背景</option>
                                <option value="證照證書">證照證書</option>
                                <option value="作品">作品</option>
                            </select>
                            <span asp-validation-for="FCategory" class="text-danger"></span>
                            <label for="floatingInput">選擇分類</label>
                        </div>
                        <!--一般文字輸入-->
                        <div class="form-floating mb-3">
                            <!-- 內容1  -->
                            <input asp-for="FImageName" class="form-control" id="floatingInput" placeholder="">
                            <!-- 標題1  -->
                            <label for="floatingInput">標題</label>
                        </div>
                        @*     <div class="form-floating mb-3">
                        <input class="form-control" id="iptdataURL">
                        </div> *@
                    </div>
                </div>
                <!-- 這個容器用來裝dropzone預設的預覽圖片 -->
                <div id="previews" style="display:flex;">  </div>
                <div class="modal-footer">
                    <input id="inpSubmit" type="button" name="file" class="btn btn-primary" value="上傳">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">關閉</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script src="https://unpkg.com/dropzone@5/dist/min/dropzone.min.js"></script>

<script>
    const formData = new FormData();
    Dropzone.options.divdropzone = {
        // 設置為 false，禁用自動處理佇列
        autoProcessQueue: false,
        // 預覽圖片放到id是previews的容器
        previewsContainer: "#previews",
        init: function () {
            this.on("success", function (file, response) {
                var progressBar = file.previewElement.querySelector(".progress-bar");
                progressBar.remove();
            });
            // this.on("success", function (file, response) {
            //     // 在上傳成功後執行的動作
            //     console.log(response); // 這裡的 response 就是伺服器回傳的資料
            // });

            // this.on("addedfile", function (file) {
            //     // 在檔案被加入佇列時執行的動作
            //     console.log(file);
            //     //console.log(dataURL);
            // });
            this.on("addedfile", function (file) {
                formData.append('f', file);
                file.accepted = true;
                // 在檔案被加入佇列時執行的動作
                var reader = new FileReader();
                reader.onload = function (e) {
                    var dataURL = e.target.result;
                    //console.log(dataURL);
                    //document.getElementById("iptdataURL").value = dataURL;
                };
                reader.readAsDataURL(file);
            });
            this.on("success", function (file, response) {
                var progressBar = file.previewElement.querySelector(".progress-bar");
                progressBar.remove();
            });
            document.getElementById('inpSubmit').addEventListener('click', function (event) {
                //取消submit的預設行為
                event.preventDefault();
                // var myDropzone = Dropzone.forElement(".dropzone");
                // console.log("into btnclick");
                // myDropzone.processQueue() ;
                //divdropzone.processQueue(); // 手動觸發上傳

                //ajax  fetch
                //FormData

                //console.log(document.querySelector('#FCategory').value);
                // const i = document.querySelector('#FCategory').selectedIndex;
                // console.log(i);
                // console.log(document.querySelector('#FCategory').options[i].text);

                //console.log(formData.get('f'));
                formData.append('FCategory', document.querySelector('#FCategory').value);
                formData.append('FImageName', document.querySelector('#floatingInput').value);
                fetch('@Url.Content("~/TeacherAdmin/TAddtrimage")', {
                    method: 'POST',
                    body: formData
                })
                // const form = event.target.closest('form');
                // Swal.fire({
                //     position: "center",
                //     icon: "success",
                //     title: "新增圖片成功",
                //     showConfirmButton: false,
                //     timer: 1500
                // }).then(() => {

                // });

                //base64 string > action > 轉成檔案儲存


                Swal.fire({
                    position: "center",
                    icon: "success",
                    title: "新增成功",
                    showConfirmButton: false,
                    timer: 1500
                }).then(() => {
                    //https://ithelp.ithome.com.tw/articles/10190062
                    //Javascript 頁面跳轉、刷新、重定向的幾種方式
                    window.location.href = '/TeacherAdmin/TRelatedPic';
                });

            });

        }



    }



    document.querySelector('#Inputfile').addEventListener('change', event => {
        //  console.log(event.target.files[0]);
        //formData.append('f', event.target.files[0]);
        const files = event.target.files;
        for (const file of files) {
            formData.append('f', file);
        }
    })
</script>
@* demo鍵 *@
<script>
    const floatingInput = document.querySelector('#floatingInput');
    const FCategory = document.querySelector('#FCategory');
    const demoCertificate = document.querySelector('#demoCertificate').addEventListener('click', (e) => {
        e.preventDefault();
        FCategory.value = '證照證書'; 
        floatingInput.value = '中餐證照';
    })
</script>